language: node_js
node_js: node
deploy:
  provider: heroku
  api_key:
    secure: Jk8kG9KHONwsEMIXXelqbR762jcVEWEiX04YQ+lQJVReXVFZpvPaci7HrpdwsilSxx7VG4LqSOB8kQzdoK456YYxsB18GACrBJAylPaJjce5t/lcHQpwa+kzoNmQzoIhJ0OYPI6Bpx+Vmr4p7vaKvNj5Za+cBovhxgvzXmguhxFbLs07DxExFbPdmuWXsXCwa4Ke1eI+/I3jvYyMIYWz4/To3xikhgq0s7sJvCkWxJx9evfRtqUOOCwvHwtbM3yGJvw2e4XHSwVQOH9T3hUD+IIc4xgqjfTBfDNU1j83JUwqIRopwHHWhVYIP8IkPFbhD6S8xSlzoB8Hq5Q4mTG2hkbhQkkwPxEsDOYsgZNkQ2TlcZtSJJ4YHkD2ceAnaHLN0nOIZVG7P+HAQm7siCRHD2kz7Ep4qul5tQWEpedtWTdXrI9r8ItZdALP/Ij8OEoZeMIeKeBbAXuWkM1iI9Jt558ClfiGO9V2ZsfRrGt4M1tputADXXllNiM975HpP585uoVNUtOFomaqOr3uGCIRvsJ3d/sCUyUpZ1f3bkaoCRv75guYydEp4HgEXzdHgvc5HD97t+b+4+LgdDS07UOujN87Pipr4aBrgQjakTDQcyjOzS2NMi0whMaAVeGKNpRtOZo4HXLwmop5w/kR7EWoX1JZwGQmVS0IaNP93eKAkCQ=
  app: murmuring-headland-28017
  on:
    repo: juanjuar457/node-shopping-list-integration-tests
